# Generated by Django 5.1.6 on 2025-02-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committee", models.CharField(max_length=250)),
                ("country", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Delegate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("user_type", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("mun_experience", models.TextField()),
                ("affiliation", models.CharField(max_length=250)),
                ("position", models.CharField(blank=True, max_length=250, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("matric_num", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=50, null=True)),
                ("advert", models.CharField(blank=True, max_length=200, null=True)),
                ("tshirt_size", models.CharField(blank=True, max_length=10, null=True)),
                ("medical", models.TextField(blank=True, null=True)),
                ("diet", models.TextField(blank=True, null=True)),
                ("referral", models.CharField(blank=True, max_length=250, null=True)),
                ("committee1", models.CharField(blank=True, max_length=250, null=True)),
                ("country1", models.CharField(blank=True, max_length=250, null=True)),
                ("committee2", models.CharField(blank=True, max_length=250, null=True)),
                ("country2", models.CharField(blank=True, max_length=250, null=True)),
                ("committee3", models.CharField(blank=True, max_length=250, null=True)),
                ("country3", models.CharField(blank=True, max_length=250, null=True)),
                ("code", models.CharField(blank=True, max_length=6, null=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="0", max_length=1)),
                ("captured", models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("committee", models.CharField(max_length=255)),
                ("preference", models.IntegerField()),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.delegate"
                    ),
                ),
            ],
        ),
    ]
