# Generated by Django 5.1.6 on 2025-02-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_delegate_status_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="committee",
            old_name="country",
            new_name="countries",
        ),
    ]
