# Generated by Django 5.1.6 on 2025-02-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_country_committee_countries"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delegate",
            old_name="user_type",
            new_name="delegate_type",
        ),
    ]
