# Generated by Django 5.1.6 on 2025-02-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_user_type_delegate_delegate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegate",
            name="advert",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("friend/colleague", "Friend/Colleague"),
                    ("university/institution", "University/Institution"),
                    ("ambassador", "Campus Ambassador"),
                    ("other", "Other"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="delegate",
            name="delegate_type",
            field=models.CharField(
                choices=[
                    ("nigerian", "Nigerian Delegate (₦70,000)"),
                    ("RUN", "Redeemer's University (₦55,000)"),
                    ("foreign", "International Delegate ($100)"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="delegate",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="delegate",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("xxl", "XXL"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
