# Generated by Django 5.1.6 on 2025-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_delegate_advert_alter_delegate_delegate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegate",
            name="affiliation",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="delegate",
            name="mun_experience",
            field=models.TextField(blank=True, null=True),
        ),
    ]
