# Generated by Django 5.1.6 on 2025-02-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_delegate_affiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.CharField(
                choices=[("Full", "Full"), ("30000", "30,000"), ("25000", "25,000")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("Portal", "Portal"),
                    ("Remita", "Remita"),
                ],
                max_length=20,
            ),
        ),
    ]
