# Generated by Django 5.1.6 on 2025-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_payment_amount_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("Portal", "Portal"),
                    ("Remita", "Remita"),
                    ("Cash", "Cash"),
                ],
                max_length=20,
            ),
        ),
    ]
